name: Update RSI Data

on:
  schedule:
    - cron: "0 5 * * 0"  # 매주 일요일 UTC 5:00 = 한국시간 14:00

jobs:
  update_rsi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install pandas yfinance gspread oauth2client

      - name: Run Python Script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: python update_rsi.py
